name: C/C++ CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: ghaction-cmake
      uses: lpenz/ghaction-cmake@v0.1
    - name: configure
      run: mkdir build; cd build; cmake ..
    - name: make test
      run: cd build; make test
    - name: Google test
      run: ./bin/tests
